import { createFileRoute } from "@tanstack/react-router";
import { Column, Kicker, Lede, Rule, Standfirst } from "../components/editorial";

export const Route = createFileRoute("/terms")({
  component: TermsPage,
  head: () => ({ meta: [{ title: "Terms — Post Pilot" }] }),
});

function TermsPage() {
  return (
    <section className="mx-auto max-w-3xl px-6 py-16 md:py-24">
      <div className="mb-12 flex flex-col gap-4">
        <Kicker>Legal</Kicker>
        <Lede as="h1" size="lg">
          Terms of Service
        </Lede>
        <Standfirst>Last updated: 2026-04-26.</Standfirst>
      </div>

      <Column>
        <p>
          These Terms of Service ("Terms") govern your access to and use of
          Post Pilot — including its website, API, and any associated services
          (collectively, the "Service") — operated by Aloe Wright ("Aloe
          Wright", "we", "us", or "our"). By accessing or using the Service,
          you agree to be bound by these Terms. If you do not agree, do not
          use the Service.
        </p>

        <h2 className="pp-lede mt-12 text-2xl">1. Eligibility</h2>
        <p>
          You must be at least 13 years old to use the Service, and at least
          the age of legal majority in your jurisdiction to enter into a
          binding contract. By using the Service, you represent that you meet
          these requirements.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">2. Accounts</h2>
        <p>
          Some features require an account. You are responsible for keeping
          your credentials secure and for all activity under your account.
          Notify us promptly of any unauthorized access. We may suspend or
          terminate accounts that violate these Terms or that put the Service
          at risk.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">3. License to use the Service</h2>
        <p>
          Subject to these Terms, Aloe Wright grants you a non-exclusive,
          non-transferable, revocable license to use the Service for personal
          or business purposes. This license does not transfer any ownership
          of the Service or its underlying intellectual property to you.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">4. Acceptable use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>
            Scrape, copy, or republish the catalog or guide content in bulk
            for the purpose of operating a competing product.
          </li>
          <li>
            Use the Service to generate unlawful, defamatory, harassing,
            infringing, or otherwise harmful content.
          </li>
          <li>
            Attempt to bypass rate limits, authentication, or other technical
            controls; reverse-engineer the Service except as permitted by
            law; or use the Service to harm others.
          </li>
          <li>
            Use the Service in any way that violates applicable law or the
            terms of any third-party service the Service relies on.
          </li>
        </ul>

        <h2 className="pp-lede mt-10 text-2xl">5. User content and outputs</h2>
        <p>
          You retain ownership of content you submit to the Service, such as
          inputs to the apply endpoint ("Inputs"). You grant Aloe Wright a
          limited license to process Inputs solely as needed to provide the
          Service. Outputs generated by the Service in response to your
          Inputs ("Outputs") belong to you to the extent permitted by
          applicable law and the terms of the underlying model providers.
          You are responsible for reviewing Outputs before relying on them.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">6. Intellectual property</h2>
        <p>
          The Service, including its software, design, branding, and
          documentation, is owned by Aloe Wright and protected by
          intellectual property laws. Each guide in the catalog is a
          curator's analytical interpretation of a writer's voice — a set of
          structured constraints and guidance, not a reproduction of any
          author's underlying text. Guides ship with a{" "}
          <code>copyright_posture</code> field that documents the position
          taken for each entry (public-domain, voice-inspired, or licensed).
          The catalog as a compilation is © Aloe Wright; individual guide
          content is © the curator named on the entry. Author names and
          biographical references are used in the descriptive sense and do
          not imply endorsement.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">7. Third-party services</h2>
        <p>
          The Service relies on third-party providers, including Cloudflare
          (for hosting, edge compute, storage, and AI Gateway routing) and
          underlying model providers accessed via that gateway. Your use of
          the Service is also subject to those providers' terms. Aloe Wright
          is not responsible for the acts or omissions of third-party
          providers.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">8. Fees</h2>
        <p>
          Some features may be free; others may require payment. Pricing,
          billing terms, and refund policy will be presented at the point of
          purchase. Aloe Wright may change pricing for paid features with
          reasonable notice; continued use after a price change constitutes
          acceptance.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">9. Termination</h2>
        <p>
          You may stop using the Service at any time. Aloe Wright may
          suspend or terminate your access for violation of these Terms,
          for legal or security reasons, or if continued operation becomes
          impractical. Sections that by their nature should survive
          termination — including ownership, disclaimers, limitations of
          liability, and dispute resolution — will survive.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">10. Disclaimer of warranties</h2>
        <p>
          THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT
          WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING WARRANTIES
          OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND
          NON-INFRINGEMENT. Aloe Wright does not warrant that the Service
          will be uninterrupted, error-free, or that Outputs will meet any
          particular quality bar — the eval rubric is a measurement tool,
          not a guarantee.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">11. Limitation of liability</h2>
        <p>
          TO THE MAXIMUM EXTENT PERMITTED BY LAW, ALOE WRIGHT WILL NOT BE
          LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL,
          EXEMPLARY, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE,
          DATA, OR GOODWILL, ARISING OUT OF OR RELATING TO YOUR USE OF THE
          SERVICE. Aloe Wright's total aggregate liability for any claim
          arising out of or relating to the Service will not exceed the
          greater of (a) the amount you paid to Aloe Wright for the Service
          in the twelve months preceding the claim, or (b) USD $50.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">12. Indemnification</h2>
        <p>
          You will indemnify and hold harmless Aloe Wright and its
          affiliates from any claim, demand, or damages arising out of your
          breach of these Terms, your misuse of the Service, or your
          violation of any law or third-party right.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">13. Governing law</h2>
        <p>
          These Terms are governed by the laws of the State of California,
          United States, without regard to its conflict-of-laws rules.
          Disputes will be resolved in the state or federal courts located
          in California, and you consent to that jurisdiction and venue.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">14. Changes</h2>
        <p>
          We may update these Terms from time to time. Material changes
          will be posted here with an updated date. Your continued use of
          the Service after changes take effect constitutes acceptance of
          the revised Terms.
        </p>

        <h2 className="pp-lede mt-10 text-2xl">15. Contact</h2>
        <p>
          Aloe Wright — questions about these Terms can be sent to{" "}
          <a href="mailto:pleasewritemealetter@gmail.com">
            pleasewritemealetter@gmail.com
          </a>
          .
        </p>

        <Rule />
      </Column>
    </section>
  );
}
