// Curated 250-author roster for Post Pilot guides.
// Each entry has: slug (kebab-case, used as filename + URL), name (display),
// era (one of the Era enum values), hint (1-2 lines that anchors the model
// when generating a voice spec — picks the dominant register/syntactic move
// so generated guides don't all collapse into the same template).

export type AuthorSeed = {
  slug: string;
  name: string;
  era: "Pre-1900" | "Modernist" | "Mid-20th" | "Late-20th" | "Contemporary";
  hint: string;
};

export const AUTHORS: AuthorSeed[] = [
  { slug: "hemingway", name: "Ernest Hemingway", era: "Modernist", hint: "iceberg theory; declarative; concrete nouns" },
  { slug: "austen", name: "Jane Austen", era: "Pre-1900", hint: "free indirect discourse; ironic distance; balanced clauses" },
  { slug: "orwell", name: "George Orwell", era: "Modernist", hint: "plain English; political clarity; six rules" },
  { slug: "didion", name: "Joan Didion", era: "Late-20th", hint: "cool diagnostic gaze; long sentences pivoting on commas; California specificity" },
  { slug: "baldwin", name: "James Baldwin", era: "Mid-20th", hint: "King James cadence; long sentences as moral argument; first-person witness" },
  { slug: "leguin", name: "Ursula K. Le Guin", era: "Late-20th", hint: "Taoist restraint; anthropological eye; quiet sentences" },
  { slug: "borges", name: "Jorge Luis Borges", era: "Modernist", hint: "labyrinths; recursive footnotes; library as cosmos" },
  { slug: "woolf", name: "Virginia Woolf", era: "Modernist", hint: "stream of consciousness; rhythm of perception; semicolon symphonies" },
  { slug: "vonnegut", name: "Kurt Vonnegut", era: "Mid-20th", hint: "short paragraphs; deadpan refrain; black humor" },
  { slug: "wilde", name: "Oscar Wilde", era: "Pre-1900", hint: "epigram; aristocratic wit; aestheticism" },
  { slug: "poe", name: "Edgar Allan Poe", era: "Pre-1900", hint: "gothic dread; trochaic cadence; first-person unreliable" },
  { slug: "carver", name: "Raymond Carver", era: "Late-20th", hint: "minimalist working-class vignettes; what is unsaid" },
  { slug: "asimov", name: "Isaac Asimov", era: "Mid-20th", hint: "lucid expository SF; dialogue carries argument" },
  { slug: "dickens", name: "Charles Dickens", era: "Pre-1900", hint: "social panorama; comic naming; serialized melodrama" },
  { slug: "twain", name: "Mark Twain", era: "Pre-1900", hint: "vernacular American; rolling river sentences; satirical drawl" },
  { slug: "melville", name: "Herman Melville", era: "Pre-1900", hint: "Shakespearean ambition; encyclopedic digression; metaphysical adventure" },
  { slug: "henry-james", name: "Henry James", era: "Pre-1900", hint: "the late style; subordinate clause architecture; psychological qualification" },
  { slug: "hawthorne", name: "Nathaniel Hawthorne", era: "Pre-1900", hint: "allegorical Puritan; dim symbolic forests; moral ambiguity" },
  { slug: "tolstoy", name: "Leo Tolstoy", era: "Pre-1900", hint: "moral realism; long social tableaux; God in the details" },
  { slug: "dostoevsky", name: "Fyodor Dostoevsky", era: "Pre-1900", hint: "polyphonic feverish dialogue; spiritual crisis; underground" },
  { slug: "chekhov", name: "Anton Chekhov", era: "Pre-1900", hint: "show don't tell; quiet revelation; provincial chamber music" },
  { slug: "flaubert", name: "Gustave Flaubert", era: "Pre-1900", hint: "le mot juste; free indirect; cold flaubertian irony" },
  { slug: "hugo", name: "Victor Hugo", era: "Pre-1900", hint: "social epic; thunderous rhetoric; digressive moral grandeur" },
  { slug: "balzac", name: "Honoré de Balzac", era: "Pre-1900", hint: "documentary social cataloguing; comédie humaine" },
  { slug: "zola", name: "Émile Zola", era: "Pre-1900", hint: "naturalist materialism; sensory accumulation; J'accuse" },
  { slug: "baudelaire", name: "Charles Baudelaire", era: "Pre-1900", hint: "spleen et idéal; urban modernity; flâneur" },
  { slug: "shelley", name: "Mary Shelley", era: "Pre-1900", hint: "Romantic gothic; framed narrative; promethean dread" },
  { slug: "charlotte-bronte", name: "Charlotte Brontë", era: "Pre-1900", hint: "first-person reader-address; governess interiority" },
  { slug: "emily-bronte", name: "Emily Brontë", era: "Pre-1900", hint: "elemental moor; nested narrators; gothic intensity" },
  { slug: "george-eliot", name: "George Eliot", era: "Pre-1900", hint: "moral psychology; long balanced periods; provincial Middlemarch" },
  { slug: "hardy", name: "Thomas Hardy", era: "Pre-1900", hint: "Wessex pastoral fatalism; geological time; rural diction" },
  { slug: "conrad", name: "Joseph Conrad", era: "Modernist", hint: "frame narrative haunting; sea as moral test; foggy density" },
  { slug: "stevenson", name: "Robert Louis Stevenson", era: "Pre-1900", hint: "muscular Scots adventure; double-self gothic" },
  { slug: "doyle", name: "Arthur Conan Doyle", era: "Pre-1900", hint: "Holmesian deduction; Watson's measured Edwardian voice" },
  { slug: "carroll", name: "Lewis Carroll", era: "Pre-1900", hint: "logical nonsense; portmanteau; Alice's literal child-logic" },
  { slug: "nietzsche", name: "Friedrich Nietzsche", era: "Pre-1900", hint: "aphoristic hammer; hyperbolic prophecy; eternal recurrence" },
  { slug: "ibsen", name: "Henrik Ibsen", era: "Pre-1900", hint: "bourgeois drama; pistol on the wall; secrets unraveling" },
  { slug: "emerson", name: "Ralph Waldo Emerson", era: "Pre-1900", hint: "transcendentalist sermon; self-reliant aphorism" },
  { slug: "thoreau", name: "Henry David Thoreau", era: "Pre-1900", hint: "Walden plain living; observed nature with civic edge" },
  { slug: "douglass", name: "Frederick Douglass", era: "Pre-1900", hint: "abolitionist oratory; classical antithesis; first-person witness" },
  { slug: "swift", name: "Jonathan Swift", era: "Pre-1900", hint: "savage indignation; deadpan satirical proposal" },
  { slug: "defoe", name: "Daniel Defoe", era: "Pre-1900", hint: "first-person plain ledger; survival realism" },
  { slug: "shaw", name: "George Bernard Shaw", era: "Pre-1900", hint: "Fabian wit; preface essays; Shavian dialogue" },
  { slug: "whitman", name: "Walt Whitman", era: "Pre-1900", hint: "long catalog free verse; barbaric yawp; democratic body" },
  { slug: "dickinson", name: "Emily Dickinson", era: "Pre-1900", hint: "compressed slant; dashes; circumference" },
  { slug: "joyce", name: "James Joyce", era: "Modernist", hint: "stream of consciousness; epiphany; multilingual play" },
  { slug: "ts-eliot", name: "T.S. Eliot", era: "Modernist", hint: "fragmented allusion; objective correlative; mythic method" },
  { slug: "pound", name: "Ezra Pound", era: "Modernist", hint: "imagist precision; make it new; dictionary of memory" },
  { slug: "yeats", name: "W.B. Yeats", era: "Modernist", hint: "symbolic Celtic; gyres; late stripped lyric" },
  { slug: "stein", name: "Gertrude Stein", era: "Modernist", hint: "repetition as insistence; continuous present; cubist syntax" },
  { slug: "fitzgerald", name: "F. Scott Fitzgerald", era: "Modernist", hint: "lyrical romantic; jazz age elegy; long lush periods" },
  { slug: "faulkner", name: "William Faulkner", era: "Modernist", hint: "Yoknapatawpha density; nested clauses; mythic South" },
  { slug: "steinbeck", name: "John Steinbeck", era: "Modernist", hint: "biblical migrant cadence; Dust Bowl realism" },
  { slug: "anderson", name: "Sherwood Anderson", era: "Modernist", hint: "Winesburg grotesques; spare American small town" },
  { slug: "cather", name: "Willa Cather", era: "Modernist", hint: "prairie monumental; classical restraint" },
  { slug: "wharton", name: "Edith Wharton", era: "Modernist", hint: "Gilded Age manners; surgical irony; long Jamesian sentences" },
  { slug: "welty", name: "Eudora Welty", era: "Mid-20th", hint: "Mississippi place-as-character; comic dialogue" },
  { slug: "oconnor", name: "Flannery O'Connor", era: "Mid-20th", hint: "Southern gothic grace; violent mercy; deadpan" },
  { slug: "porter", name: "Katherine Anne Porter", era: "Modernist", hint: "polished Texan; long story arc compressed" },
  { slug: "parker", name: "Dorothy Parker", era: "Modernist", hint: "Algonquin wit; barbed light verse" },
  { slug: "lawrence", name: "D.H. Lawrence", era: "Modernist", hint: "primal vitalism; rhythmic incantation; Lawrence's preacher pulse" },
  { slug: "forster", name: "E.M. Forster", era: "Modernist", hint: "only connect; Edwardian liberal irony; modest periodic sentences" },
  { slug: "huxley", name: "Aldous Huxley", era: "Modernist", hint: "essayistic dystopia; cool ideational prose" },
  { slug: "waugh", name: "Evelyn Waugh", era: "Mid-20th", hint: "savage social comedy; deadpan brittleness" },
  { slug: "greene", name: "Graham Greene", era: "Mid-20th", hint: "Catholic moral thriller; reportorial cool; sin and grace" },
  { slug: "kafka", name: "Franz Kafka", era: "Modernist", hint: "bureaucratic dread; lucid German; absurd procedural" },
  { slug: "mann", name: "Thomas Mann", era: "Modernist", hint: "ironic Bildungsroman; long German periods; Apollonian" },
  { slug: "hesse", name: "Hermann Hesse", era: "Modernist", hint: "spiritual quest fable; clear German; Eastern parable" },
  { slug: "proust", name: "Marcel Proust", era: "Modernist", hint: "involuntary memory; cathedral sentence; Combray cadence" },
  { slug: "camus", name: "Albert Camus", era: "Mid-20th", hint: "absurdist clarity; Mediterranean light; first-person testimony" },
  { slug: "sartre", name: "Jean-Paul Sartre", era: "Mid-20th", hint: "existential nausea; phenomenological essay; commitment" },
  { slug: "beauvoir", name: "Simone de Beauvoir", era: "Mid-20th", hint: "existential feminism; analytical autobiography" },
  { slug: "neruda", name: "Pablo Neruda", era: "Modernist", hint: "telluric ode; Spanish surge; political tenderness" },
  { slug: "lorca", name: "Federico García Lorca", era: "Modernist", hint: "duende; Andalusian image; surrealist gypsy" },
  { slug: "rulfo", name: "Juan Rulfo", era: "Mid-20th", hint: "ghostly Mexican plains; pared dialogue; Pedro Páramo silences" },
  { slug: "lu-xun", name: "Lu Xun", era: "Modernist", hint: "vernacular reform; biting essayistic fiction; Chinese 20th-c. clarity" },
  { slug: "bradbury", name: "Ray Bradbury", era: "Mid-20th", hint: "lyric SF; nostalgia; small-town carnival" },
  { slug: "philip-k-dick", name: "Philip K. Dick", era: "Mid-20th", hint: "paranoid metaphysical SF; reality slipping" },
  { slug: "clarke", name: "Arthur C. Clarke", era: "Mid-20th", hint: "cool British engineering SF; cosmic awe" },
  { slug: "heinlein", name: "Robert Heinlein", era: "Mid-20th", hint: "competent-man libertarian SF; wisecracking" },
  { slug: "salinger", name: "J.D. Salinger", era: "Mid-20th", hint: "Holden cadence; phony detector; Glass family knowingness" },
  { slug: "updike", name: "John Updike", era: "Late-20th", hint: "lyric suburban; perceptual sentences; Rabbit's pewter glint" },
  { slug: "bellow", name: "Saul Bellow", era: "Mid-20th", hint: "Chicago intellectual maximalism; Yiddish-inflected energy" },
  { slug: "philip-roth", name: "Philip Roth", era: "Late-20th", hint: "Newark fury; relentless amplification; Zuckerman riffs" },
  { slug: "mailer", name: "Norman Mailer", era: "Mid-20th", hint: "swaggering New Journalism; metaphysical pugilism" },
  { slug: "capote", name: "Truman Capote", era: "Mid-20th", hint: "lapidary Southern; nonfiction novel cool" },
  { slug: "tennessee-williams", name: "Tennessee Williams", era: "Mid-20th", hint: "Southern lyric drama; longing; gauzy fans" },
  { slug: "miller", name: "Arthur Miller", era: "Mid-20th", hint: "American moral drama; Loman cadence" },
  { slug: "beckett", name: "Samuel Beckett", era: "Mid-20th", hint: "stripped-down absurd; pause; ellipsis" },
  { slug: "pinter", name: "Harold Pinter", era: "Mid-20th", hint: "menacing pause; working-class British rhythm" },
  { slug: "stoppard", name: "Tom Stoppard", era: "Late-20th", hint: "ideational wit; punning theatricality" },
  { slug: "murdoch", name: "Iris Murdoch", era: "Mid-20th", hint: "philosophical novelist; moral attention; Platonic Eros" },
  { slug: "lessing", name: "Doris Lessing", era: "Late-20th", hint: "Golden Notebook; political realism; SF allegory" },
  { slug: "spark", name: "Muriel Spark", era: "Mid-20th", hint: "wickedly economical; flash-forward; cool Edinburgh edge" },
  { slug: "amis-kingsley", name: "Kingsley Amis", era: "Mid-20th", hint: "Lucky Jim comic; provincial pub" },
  { slug: "burgess", name: "Anthony Burgess", era: "Mid-20th", hint: "Nadsat invented argot; musical playful" },
  { slug: "le-carre", name: "John le Carré", era: "Late-20th", hint: "Cold War tradecraft; deflated empire; Smiley's silences" },
  { slug: "highsmith", name: "Patricia Highsmith", era: "Mid-20th", hint: "amoral interior thriller; Ripley's calm" },
  { slug: "chandler", name: "Raymond Chandler", era: "Modernist", hint: "hardboiled simile; Marlowe's first-person LA" },
  { slug: "hammett", name: "Dashiell Hammett", era: "Modernist", hint: "stripped third-person noir; Continental Op" },
  { slug: "shirley-jackson", name: "Shirley Jackson", era: "Mid-20th", hint: "domestic gothic; quiet menace; Hill House cadence" },
  { slug: "mccullers", name: "Carson McCullers", era: "Mid-20th", hint: "Southern outsider lyric; mute longing" },
  { slug: "cheever", name: "John Cheever", era: "Mid-20th", hint: "suburban myth; swimmer's pool; lyrical melancholy" },
  { slug: "barthelme", name: "Donald Barthelme", era: "Late-20th", hint: "fragmentary collage; ironic short paragraphs" },
  { slug: "calvino", name: "Italo Calvino", era: "Mid-20th", hint: "lightness; combinatorial fable; invisible city" },
  { slug: "levi", name: "Primo Levi", era: "Mid-20th", hint: "chemist's clarity; testimony; controlled witness" },
  { slug: "garcia-marquez", name: "Gabriel García Márquez", era: "Late-20th", hint: "magical realism; sentence-long sentences; Macondo memory" },
  { slug: "vargas-llosa", name: "Mario Vargas Llosa", era: "Late-20th", hint: "polyphonic Peru; intercut dialogue" },
  { slug: "cortazar", name: "Julio Cortázar", era: "Mid-20th", hint: "playful labyrinth; Hopscotch reader-game" },
  { slug: "fuentes", name: "Carlos Fuentes", era: "Mid-20th", hint: "Mexican historical baroque" },
  { slug: "lispector", name: "Clarice Lispector", era: "Mid-20th", hint: "luminous interior; mystical Brazilian; sentence as breath" },
  { slug: "grass", name: "Günter Grass", era: "Mid-20th", hint: "Tin Drum carnival; postwar German guilt" },
  { slug: "boll", name: "Heinrich Böll", era: "Mid-20th", hint: "spare West German moral realism" },
  { slug: "solzhenitsyn", name: "Aleksandr Solzhenitsyn", era: "Mid-20th", hint: "labor camp testimony; gritty Russian moral" },
  { slug: "nabokov", name: "Vladimir Nabokov", era: "Mid-20th", hint: "lepidopteran precision; punning trilingual; aesthetic bliss" },
  { slug: "sontag", name: "Susan Sontag", era: "Late-20th", hint: "essayistic European; against interpretation; declarative aphorism" },
  { slug: "arendt", name: "Hannah Arendt", era: "Mid-20th", hint: "political philosophy; banality of evil; long German-inflected English" },
  { slug: "barthes", name: "Roland Barthes", era: "Mid-20th", hint: "fragmentary semiotic; lover's discourse; mythologies" },
  { slug: "foucault", name: "Michel Foucault", era: "Late-20th", hint: "archaeological power-knowledge; long French periodics" },
  { slug: "mccarthy-mary", name: "Mary McCarthy", era: "Mid-20th", hint: "sharp memoir intellectual; New York critic" },
  { slug: "morrison", name: "Toni Morrison", era: "Late-20th", hint: "African American epic lyric; choric rhythm; Beloved interior" },
  { slug: "delillo", name: "Don DeLillo", era: "Late-20th", hint: "paranoid postmodern; American din; clinical distance" },
  { slug: "pynchon", name: "Thomas Pynchon", era: "Late-20th", hint: "paranoid encyclopedic; song-and-pun; entropy" },
  { slug: "cormac-mccarthy", name: "Cormac McCarthy", era: "Late-20th", hint: "biblical violence; conjunctive run-on; no quotes" },
  { slug: "gaddis", name: "William Gaddis", era: "Late-20th", hint: "all dialogue; corporate entropy; long unattributed exchange" },
  { slug: "dfw", name: "David Foster Wallace", era: "Late-20th", hint: "footnoted maximalism; recursive irony; tennis-net qualifications" },
  { slug: "franzen", name: "Jonathan Franzen", era: "Contemporary", hint: "social novel; family system; controlled exasperation" },
  { slug: "dillard", name: "Annie Dillard", era: "Late-20th", hint: "natural-philosophy lyric; pilgrim attention" },
  { slug: "hempel", name: "Amy Hempel", era: "Late-20th", hint: "compressed flash; precise wound; minimalism after Carver" },
  { slug: "lorrie-moore", name: "Lorrie Moore", era: "Late-20th", hint: "puns and grief; suburban ache" },
  { slug: "denis-johnson", name: "Denis Johnson", era: "Late-20th", hint: "Jesus' Son fevered; addict lyric" },
  { slug: "ford", name: "Richard Ford", era: "Late-20th", hint: "Frank Bascombe drift; New Jersey middle distance" },
  { slug: "wolff", name: "Tobias Wolff", era: "Late-20th", hint: "memoiristic precision; This Boy's Life" },
  { slug: "atwood", name: "Margaret Atwood", era: "Late-20th", hint: "Canadian sardonic; speculative dystopia" },
  { slug: "munro", name: "Alice Munro", era: "Late-20th", hint: "Ontario small-town; time-folded short story" },
  { slug: "ondaatje", name: "Michael Ondaatje", era: "Late-20th", hint: "fragmentary lyrical novel; postcolonial collage" },
  { slug: "rushdie", name: "Salman Rushdie", era: "Late-20th", hint: "magical realist Indian English; chutnified syntax" },
  { slug: "naipaul", name: "V.S. Naipaul", era: "Late-20th", hint: "diasporic cool; classical English; mordant observation" },
  { slug: "ishiguro", name: "Kazuo Ishiguro", era: "Late-20th", hint: "controlled first-person; restrained English; reliable narrator hiding things" },
  { slug: "mantel", name: "Hilary Mantel", era: "Contemporary", hint: "Cromwell present-tense interior; Tudor close-third" },
  { slug: "barnes", name: "Julian Barnes", era: "Late-20th", hint: "essayistic novel; ironic Englishness" },
  { slug: "mcewan", name: "Ian McEwan", era: "Late-20th", hint: "controlled menace; surgical sentences" },
  { slug: "amis-martin", name: "Martin Amis", era: "Late-20th", hint: "thesaurus muscularity; London comic dread" },
  { slug: "angela-carter", name: "Angela Carter", era: "Late-20th", hint: "feminist gothic fairy tale; lush ornament" },
  { slug: "welsh", name: "Irvine Welsh", era: "Late-20th", hint: "Edinburgh phonetic vernacular; dialect-as-form" },
  { slug: "kelman", name: "James Kelman", era: "Late-20th", hint: "Glasgow inner voice; demotic stream" },
  { slug: "bolano", name: "Roberto Bolaño", era: "Contemporary", hint: "literary noir; Latin American underground" },
  { slug: "allende", name: "Isabel Allende", era: "Late-20th", hint: "magical-realist family epic; Chilean lyric" },
  { slug: "achebe", name: "Chinua Achebe", era: "Late-20th", hint: "Igbo proverb; postcolonial parable; quiet authority" },
  { slug: "soyinka", name: "Wole Soyinka", era: "Late-20th", hint: "Yoruba mythic English; Nigerian baroque" },
  { slug: "ngugi", name: "Ngũgĩ wa Thiong'o", era: "Late-20th", hint: "decolonial Gikuyu; political clarity" },
  { slug: "gordimer", name: "Nadine Gordimer", era: "Late-20th", hint: "South African moral realism; long observed sentences" },
  { slug: "coetzee", name: "J.M. Coetzee", era: "Late-20th", hint: "austere allegory; cool present-tense; ethical pressure" },
  { slug: "octavia-butler", name: "Octavia Butler", era: "Late-20th", hint: "afrofuturist parable; bodily SF" },
  { slug: "delany", name: "Samuel R. Delany", era: "Late-20th", hint: "dense semiotic SF; Black queer New Wave" },
  { slug: "gibson", name: "William Gibson", era: "Late-20th", hint: "noir cyberpunk; brand-name surfaces; close-third street" },
  { slug: "stephenson", name: "Neal Stephenson", era: "Late-20th", hint: "techno-encyclopedic; comic ranging info-dump" },
  { slug: "iain-banks", name: "Iain M. Banks", era: "Late-20th", hint: "post-scarcity Culture; sardonic Scots" },
  { slug: "erdrich", name: "Louise Erdrich", era: "Late-20th", hint: "Ojibwe braided novel; mythic interlocking" },
  { slug: "cisneros", name: "Sandra Cisneros", era: "Late-20th", hint: "Chicana lyric vignettes; Mango Street" },
  { slug: "junot-diaz", name: "Junot Díaz", era: "Late-20th", hint: "Dominican-American Spanglish; nerdy first-person bravado" },
  { slug: "lahiri", name: "Jhumpa Lahiri", era: "Contemporary", hint: "diasporic precision; quiet domestic restraint" },
  { slug: "danticat", name: "Edwidge Danticat", era: "Late-20th", hint: "Haitian-American lyric; intergenerational testimony" },
  { slug: "marilynne-robinson", name: "Marilynne Robinson", era: "Contemporary", hint: "Calvinist hush; Iowa light; theological cadence" },
  { slug: "saunders", name: "George Saunders", era: "Contemporary", hint: "warm satiric voice; corporate dystopia; tender comedy" },
  { slug: "lydia-davis", name: "Lydia Davis", era: "Contemporary", hint: "miniature analytical fiction; one-paragraph stories" },
  { slug: "egan", name: "Jennifer Egan", era: "Contemporary", hint: "structurally inventive; Goon Squad time skips" },
  { slug: "chabon", name: "Michael Chabon", era: "Contemporary", hint: "lush genre-loving; Jewish-American maximalism" },
  { slug: "lethem", name: "Jonathan Lethem", era: "Contemporary", hint: "Brooklyn pop polymath; genre-blender" },
  { slug: "powers", name: "Richard Powers", era: "Contemporary", hint: "scientific encyclopedic; ecological awe" },
  { slug: "karen-russell", name: "Karen Russell", era: "Contemporary", hint: "Floridian magical-realist; bestiary of imagery" },
  { slug: "groff", name: "Lauren Groff", era: "Contemporary", hint: "lush mythic American; controlled lyric" },
  { slug: "doerr", name: "Anthony Doerr", era: "Contemporary", hint: "luminous historical; short-chapter mosaic" },
  { slug: "whitehead", name: "Colson Whitehead", era: "Contemporary", hint: "elastic Black American voice; ironic distance" },
  { slug: "gyasi", name: "Yaa Gyasi", era: "Contemporary", hint: "Ghanaian-American generational; restrained chapter-as-life" },
  { slug: "coates", name: "Ta-Nehisi Coates", era: "Contemporary", hint: "letter-form essay; Baldwin-inflected; political clarity" },
  { slug: "roxane-gay", name: "Roxane Gay", era: "Contemporary", hint: "frank essayistic; bad feminist; declarative" },
  { slug: "jesmyn-ward", name: "Jesmyn Ward", era: "Contemporary", hint: "Mississippi lyrical; ghosts; family elegy" },
  { slug: "ben-lerner", name: "Ben Lerner", era: "Contemporary", hint: "autofictional poetic essay; metafictional" },
  { slug: "rachel-cusk", name: "Rachel Cusk", era: "Contemporary", hint: "Outline negative-space first-person; listening narrator" },
  { slug: "ali-smith", name: "Ali Smith", era: "Contemporary", hint: "punning Scottish; topical seasonal cycle" },
  { slug: "n-k-jemisin", name: "N.K. Jemisin", era: "Contemporary", hint: "second-person epic fantasy; geological violence" },
  { slug: "ted-chiang", name: "Ted Chiang", era: "Contemporary", hint: "philosophical SF parable; lucid hard idea" },
  { slug: "liu-cixin", name: "Liu Cixin", era: "Contemporary", hint: "cosmic-scale Chinese SF; expository awe" },
  { slug: "han-kang", name: "Han Kang", era: "Contemporary", hint: "Korean haunted prose; bodily memory; quiet violence" },
  { slug: "murakami", name: "Haruki Murakami", era: "Late-20th", hint: "magical pop melancholy; well-wells; jazz-prose" },
  { slug: "yoko-ogawa", name: "Yoko Ogawa", era: "Contemporary", hint: "Japanese unsettling miniatures; cool restrained" },
  { slug: "mo-yan", name: "Mo Yan", era: "Contemporary", hint: "rural Chinese folk-magical; sensory excess" },
  { slug: "min-jin-lee", name: "Min Jin Lee", era: "Contemporary", hint: "Korean-American historical realism; multi-generational" },
  { slug: "adichie", name: "Chimamanda Ngozi Adichie", era: "Contemporary", hint: "Nigerian transatlantic; sharp third-person; Americanah" },
  { slug: "teju-cole", name: "Teju Cole", era: "Contemporary", hint: "Open City peripatetic essay; cosmopolitan flâneur" },
  { slug: "aravind-adiga", name: "Aravind Adiga", era: "Contemporary", hint: "Indian satirical first-person; class fury" },
  { slug: "arundhati-roy", name: "Arundhati Roy", era: "Late-20th", hint: "lush Kerala lyric; political fury" },
  { slug: "vikram-seth", name: "Vikram Seth", era: "Late-20th", hint: "Suitable Boy classical; chiseled novelistic verse" },
  { slug: "knausgard", name: "Karl Ove Knausgård", era: "Contemporary", hint: "Norwegian autofiction; granular daily; long discursive" },
  { slug: "tokarczuk", name: "Olga Tokarczuk", era: "Contemporary", hint: "Polish constellation novel; tender encyclopedism" },
  { slug: "ferrante", name: "Elena Ferrante", era: "Contemporary", hint: "Neapolitan friendship; relentless first-person" },
  { slug: "ernaux", name: "Annie Ernaux", era: "Contemporary", hint: "auto-sociological; declarative bare French" },
  { slug: "modiano", name: "Patrick Modiano", era: "Contemporary", hint: "Parisian memory-haunt; Occupation; thin spectral chapters" },
  { slug: "kerangal", name: "Maylis de Kerangal", era: "Contemporary", hint: "long French periodic; technical procedure as lyric" },
  { slug: "slimani", name: "Leïla Slimani", era: "Contemporary", hint: "Franco-Moroccan precise present-tense" },
  { slug: "tom-wolfe", name: "Tom Wolfe", era: "Late-20th", hint: "New Journalism pyrotechnic punctuation; status detail" },
  { slug: "hunter-thompson", name: "Hunter S. Thompson", era: "Late-20th", hint: "Gonzo first-person; drug-drenched political invective" },
  { slug: "talese", name: "Gay Talese", era: "Mid-20th", hint: "elegant literary journalism; Sinatra has a Cold" },
  { slug: "mcphee", name: "John McPhee", era: "Late-20th", hint: "structurally precise reportage; geological time; New Yorker rhythm" },
  { slug: "orlean", name: "Susan Orlean", era: "Contemporary", hint: "warm curious profile; New Yorker portrait" },
  { slug: "janet-malcolm", name: "Janet Malcolm", era: "Late-20th", hint: "cool ethical interrogation; journalist as moral problem" },
  { slug: "gladwell", name: "Malcolm Gladwell", era: "Contemporary", hint: "anecdote-led pop social science; rule of three" },
  { slug: "sedaris", name: "David Sedaris", era: "Contemporary", hint: "deadpan diary humor; family vignette" },
  { slug: "joseph-mitchell", name: "Joseph Mitchell", era: "Mid-20th", hint: "old New Yorker city portrait; humane patient detail" },
  { slug: "kapuscinski", name: "Ryszard Kapuściński", era: "Late-20th", hint: "Polish global reportage; mythic third world" },
  { slug: "chatwin", name: "Bruce Chatwin", era: "Late-20th", hint: "wandering travel essay; songlines fragmentary" },
  { slug: "theroux", name: "Paul Theroux", era: "Late-20th", hint: "acerbic train travel; American grouch abroad" },
  { slug: "geoff-dyer", name: "Geoff Dyer", era: "Contemporary", hint: "essayistic drift; book about not writing" },
  { slug: "solnit", name: "Rebecca Solnit", era: "Contemporary", hint: "essayistic feminist landscape; Field Guide cadence" },
  { slug: "maggie-nelson", name: "Maggie Nelson", era: "Contemporary", hint: "autotheory fragment; quotation collage" },
  { slug: "mary-karr", name: "Mary Karr", era: "Contemporary", hint: "Texan memoir verse; Liar's Club drawl" },
  { slug: "anne-carson", name: "Anne Carson", era: "Contemporary", hint: "classicist fragmentary; lyric essay-poem" },
  { slug: "mary-oliver", name: "Mary Oliver", era: "Contemporary", hint: "plain attentive nature poem; American transcendental" },
  { slug: "heaney", name: "Seamus Heaney", era: "Late-20th", hint: "Irish bog earth; muscular consonants" },
  { slug: "claudia-rankine", name: "Claudia Rankine", era: "Contemporary", hint: "documentary lyric essay; second-person Black witness" },
  { slug: "frank-ohara", name: "Frank O'Hara", era: "Mid-20th", hint: "lunch poems; New York ebullience; offhand specifics" },
  { slug: "ashbery", name: "John Ashbery", era: "Late-20th", hint: "discursive associative; flat surreal Americana" },
  { slug: "plath", name: "Sylvia Plath", era: "Mid-20th", hint: "confessional violence; sonic compression" },
  { slug: "gluck", name: "Louise Glück", era: "Late-20th", hint: "stripped severe lyric; mythic plain" },
  { slug: "jia-tolentino", name: "Jia Tolentino", era: "Contemporary", hint: "internet-aware essayist; long argument-as-essay" },
  { slug: "sorkin", name: "Aaron Sorkin", era: "Contemporary", hint: "walk-and-talk; cadenced banter; idealist monologue" },
  { slug: "mamet", name: "David Mamet", era: "Late-20th", hint: "staccato profanity; salesman's truncated demand" },
  { slug: "tony-kushner", name: "Tony Kushner", era: "Late-20th", hint: "Angels in America operatic; political queer baroque" },
  { slug: "phoebe-waller-bridge", name: "Phoebe Waller-Bridge", era: "Contemporary", hint: "fourth-wall break; British self-aware comic dread" },
  { slug: "tina-fey", name: "Tina Fey", era: "Contemporary", hint: "improv-comic memoir; sharp self-deprecating" },
  { slug: "nora-ephron", name: "Nora Ephron", era: "Late-20th", hint: "warm comic essay; everything is copy" },
  { slug: "sloane-crosley", name: "Sloane Crosley", era: "Contemporary", hint: "dryly comic personal essay" },
  { slug: "carl-sagan", name: "Carl Sagan", era: "Late-20th", hint: "cosmic awe popular science; pale blue dot" },
  { slug: "stephen-jay-gould", name: "Stephen Jay Gould", era: "Late-20th", hint: "essayistic evolutionary; baseball metaphor" },
  { slug: "oliver-sacks", name: "Oliver Sacks", era: "Late-20th", hint: "neurological case study; humanist clinician" },
  { slug: "lewis-thomas", name: "Lewis Thomas", era: "Late-20th", hint: "biological essayist; cell as community" },
  { slug: "bill-bryson", name: "Bill Bryson", era: "Contemporary", hint: "amused expat travel-and-curiosity" },
  { slug: "mary-roach", name: "Mary Roach", era: "Contemporary", hint: "wry science reportage; bodily curiosity" },
  { slug: "siddhartha-mukherjee", name: "Siddhartha Mukherjee", era: "Contemporary", hint: "physician essayist; cancer biography" },
  { slug: "atul-gawande", name: "Atul Gawande", era: "Contemporary", hint: "surgeon-essayist; checklist clarity" },
  { slug: "berger", name: "John Berger", era: "Late-20th", hint: "Ways of Seeing essayistic; political art writing" },
  { slug: "bell-hooks", name: "bell hooks", era: "Late-20th", hint: "Black feminist plain accessible; pedagogical" },
  { slug: "audre-lorde", name: "Audre Lorde", era: "Mid-20th", hint: "Black queer essay; sister outsider; declarative" },
  { slug: "edward-said", name: "Edward Said", era: "Late-20th", hint: "Orientalism erudite; Palestinian humanist" },
  { slug: "cornel-west", name: "Cornel West", era: "Contemporary", hint: "prophetic Black intellectual; Du Boisian cadence" },
  { slug: "mencken", name: "H.L. Mencken", era: "Modernist", hint: "Baltimore curmudgeon; Latinate insult" },
  { slug: "eb-white", name: "E.B. White", era: "Mid-20th", hint: "New Yorker plain elegance; Strunk-and-White restraint" },
  { slug: "trillin", name: "Calvin Trillin", era: "Late-20th", hint: "warm comic food essay" },
  { slug: "watterson", name: "Bill Watterson", era: "Late-20th", hint: "Calvin and Hobbes voice — kid bombast + strip wit" },
];
