// Curated 250-author roster for Post Pilot guides.
// Each entry has: slug (kebab-case, used as filename + URL), name (display),
// era (one of the Era enum values), hint (1-2 lines that anchors the model
// when generating a voice spec — picks the dominant register/syntactic move
// so generated guides don't all collapse into the same template).

export type AuthorSeed = {
  slug: string;
  name: string;
  era: "Pre-1900" | "Modernist" | "Mid-20th" | "Late-20th" | "Contemporary";
  hint: string;
};

export const AUTHORS: AuthorSeed[] = [
  { slug: "hemingway", name: "Ernest Hemingway", era: "Modernist", hint: "iceberg theory; declarative; concrete nouns" },
  { slug: "austen", name: "Jane Austen", era: "Pre-1900", hint: "free indirect discourse; ironic distance; balanced clauses" },
  { slug: "woolf", name: "Virginia Woolf", era: "Modernist", hint: "stream of consciousness; rhythm of perception; semicolon symphonies" },
  { slug: "vonnegut", name: "Kurt Vonnegut", era: "Mid-20th", hint: "short paragraphs; deadpan refrain; black humor" },
  { slug: "wilde", name: "Oscar Wilde", era: "Pre-1900", hint: "epigram; aristocratic wit; aestheticism" },
  { slug: "poe", name: "Edgar Allan Poe", era: "Pre-1900", hint: "gothic dread; trochaic cadence; first-person unreliable" },
  { slug: "asimov", name: "Isaac Asimov", era: "Mid-20th", hint: "lucid expository SF; dialogue carries argument" },
  { slug: "dickens", name: "Charles Dickens", era: "Pre-1900", hint: "social panorama; comic naming; serialized melodrama" },
  { slug: "twain", name: "Mark Twain", era: "Pre-1900", hint: "vernacular American; rolling river sentences; satirical drawl" },
  { slug: "melville", name: "Herman Melville", era: "Pre-1900", hint: "Shakespearean ambition; encyclopedic digression; metaphysical adventure" },
  { slug: "henry-james", name: "Henry James", era: "Pre-1900", hint: "the late style; subordinate clause architecture; psychological qualification" },
  { slug: "hawthorne", name: "Nathaniel Hawthorne", era: "Pre-1900", hint: "allegorical Puritan; dim symbolic forests; moral ambiguity" },
  { slug: "tolstoy", name: "Leo Tolstoy", era: "Pre-1900", hint: "moral realism; long social tableaux; God in the details" },
  { slug: "chekhov", name: "Anton Chekhov", era: "Pre-1900", hint: "show don't tell; quiet revelation; provincial chamber music" },
  { slug: "flaubert", name: "Gustave Flaubert", era: "Pre-1900", hint: "le mot juste; free indirect; cold flaubertian irony" },
  { slug: "hugo", name: "Victor Hugo", era: "Pre-1900", hint: "social epic; thunderous rhetoric; digressive moral grandeur" },
  { slug: "balzac", name: "Honoré de Balzac", era: "Pre-1900", hint: "documentary social cataloguing; comédie humaine" },
  { slug: "zola", name: "Émile Zola", era: "Pre-1900", hint: "naturalist materialism; sensory accumulation; J'accuse" },
  { slug: "baudelaire", name: "Charles Baudelaire", era: "Pre-1900", hint: "spleen et idéal; urban modernity; flâneur" },
  { slug: "shelley", name: "Mary Shelley", era: "Pre-1900", hint: "Romantic gothic; framed narrative; promethean dread" },
  { slug: "charlotte-bronte", name: "Charlotte Brontë", era: "Pre-1900", hint: "first-person reader-address; governess interiority" },
  { slug: "emily-bronte", name: "Emily Brontë", era: "Pre-1900", hint: "elemental moor; nested narrators; gothic intensity" },
  { slug: "george-eliot", name: "George Eliot", era: "Pre-1900", hint: "moral psychology; long balanced periods; provincial Middlemarch" },
  { slug: "hardy", name: "Thomas Hardy", era: "Pre-1900", hint: "Wessex pastoral fatalism; geological time; rural diction" },
  { slug: "conrad", name: "Joseph Conrad", era: "Modernist", hint: "frame narrative haunting; sea as moral test; foggy density" },
  { slug: "stevenson", name: "Robert Louis Stevenson", era: "Pre-1900", hint: "muscular Scots adventure; double-self gothic" },
  { slug: "doyle", name: "Arthur Conan Doyle", era: "Pre-1900", hint: "Holmesian deduction; Watson's measured Edwardian voice" },
  { slug: "carroll", name: "Lewis Carroll", era: "Pre-1900", hint: "logical nonsense; portmanteau; Alice's literal child-logic" },
  { slug: "nietzsche", name: "Friedrich Nietzsche", era: "Pre-1900", hint: "aphoristic hammer; hyperbolic prophecy; eternal recurrence" },
  { slug: "ibsen", name: "Henrik Ibsen", era: "Pre-1900", hint: "bourgeois drama; pistol on the wall; secrets unraveling" },
  { slug: "emerson", name: "Ralph Waldo Emerson", era: "Pre-1900", hint: "transcendentalist sermon; self-reliant aphorism" },
  { slug: "thoreau", name: "Henry David Thoreau", era: "Pre-1900", hint: "Walden plain living; observed nature with civic edge" },
  { slug: "douglass", name: "Frederick Douglass", era: "Pre-1900", hint: "abolitionist oratory; classical antithesis; first-person witness" },
  { slug: "swift", name: "Jonathan Swift", era: "Pre-1900", hint: "savage indignation; deadpan satirical proposal" },
  { slug: "defoe", name: "Daniel Defoe", era: "Pre-1900", hint: "first-person plain ledger; survival realism" },
  { slug: "whitman", name: "Walt Whitman", era: "Pre-1900", hint: "long catalog free verse; barbaric yawp; democratic body" },
  { slug: "dickinson", name: "Emily Dickinson", era: "Pre-1900", hint: "compressed slant; dashes; circumference" },
  { slug: "joyce", name: "James Joyce", era: "Modernist", hint: "stream of consciousness; epiphany; multilingual play" },
  { slug: "pound", name: "Ezra Pound", era: "Modernist", hint: "imagist precision; make it new; dictionary of memory" },
  { slug: "stein", name: "Gertrude Stein", era: "Modernist", hint: "repetition as insistence; continuous present; cubist syntax" },
  { slug: "fitzgerald", name: "F. Scott Fitzgerald", era: "Modernist", hint: "lyrical romantic; jazz age elegy; long lush periods" },
  { slug: "faulkner", name: "William Faulkner", era: "Modernist", hint: "Yoknapatawpha density; nested clauses; mythic South" },
  { slug: "anderson", name: "Sherwood Anderson", era: "Modernist", hint: "Winesburg grotesques; spare American small town" },
  { slug: "cather", name: "Willa Cather", era: "Modernist", hint: "prairie monumental; classical restraint" },
  { slug: "wharton", name: "Edith Wharton", era: "Modernist", hint: "Gilded Age manners; surgical irony; long Jamesian sentences" },
  { slug: "huxley", name: "Aldous Huxley", era: "Modernist", hint: "essayistic dystopia; cool ideational prose" },
  { slug: "kafka", name: "Franz Kafka", era: "Modernist", hint: "bureaucratic dread; lucid German; absurd procedural" },
  { slug: "mann", name: "Thomas Mann", era: "Modernist", hint: "ironic Bildungsroman; long German periods; Apollonian" },
  { slug: "hesse", name: "Hermann Hesse", era: "Modernist", hint: "spiritual quest fable; clear German; Eastern parable" },
  { slug: "proust", name: "Marcel Proust", era: "Modernist", hint: "involuntary memory; cathedral sentence; Combray cadence" },
  { slug: "bradbury", name: "Ray Bradbury", era: "Mid-20th", hint: "lyric SF; nostalgia; small-town carnival" },
  { slug: "philip-k-dick", name: "Philip K. Dick", era: "Mid-20th", hint: "paranoid metaphysical SF; reality slipping" },
  { slug: "hammett", name: "Dashiell Hammett", era: "Modernist", hint: "stripped third-person noir; Continental Op" },
  { slug: "anthony-trollope", name: "Anthony Trollope", era: "Pre-1900", hint: "patient clerical realism; intrusive narrator weighing motives; long balanced clauses with ironic qualification" },
  { slug: "elizabeth-gaskell", name: "Elizabeth Gaskell", era: "Pre-1900", hint: "industrial-pastoral sympathy; quiet free indirect discourse drifting between gentry and millworker registers" },
  { slug: "wilkie-collins", name: "Wilkie Collins", era: "Pre-1900", hint: "multi-voice testimonial sensation novel; legalistic deposition cadence; cliffhanger chapter-ends" },
  { slug: "stephen-crane", name: "Stephen Crane", era: "Pre-1900", hint: "naturalist impressionism; clipped present-tense color words; ironic detachment from heroic rhetoric" },
  { slug: "frank-norris", name: "Frank Norris", era: "Pre-1900", hint: "muscular naturalism with operatic crescendo; freight-train sentences piling industrial nouns" },
  { slug: "william-dean-howells", name: "William Dean Howells", era: "Pre-1900", hint: "genteel realist drawing-room dialogue; mild irony; precise middle-distance social observation" },
  { slug: "ambrose-bierce", name: "Ambrose Bierce", era: "Pre-1900", hint: "epigrammatic cynicism; crisp military precision; trapdoor twist endings" },
  { slug: "bret-harte", name: "Bret Harte", era: "Pre-1900", hint: "frontier sentimentalism; mock-heroic camp-vernacular framed by elevated narrator" },
  { slug: "sarah-orne-jewett", name: "Sarah Orne Jewett", era: "Pre-1900", hint: "Maine-coast local color; understated paratactic sketches; quiet observational stillness" },
  { slug: "kate-chopin", name: "Kate Chopin", era: "Pre-1900", hint: "Creole interior monologue; restrained lyric sensuality; abrupt awakenings of self" },
  { slug: "charlotte-perkins-gilman", name: "Charlotte Perkins Gilman", era: "Pre-1900", hint: "fragmented diary first person; nervous repetition; feminist allegory bleeding through domestic detail" },
  { slug: "harriet-beecher-stowe", name: "Harriet Beecher Stowe", era: "Pre-1900", hint: "evangelical sentimental address; direct apostrophes to reader; abolitionist moral crescendo" },
  { slug: "louisa-may-alcott", name: "Louisa May Alcott", era: "Pre-1900", hint: "domestic warmth with brisk pedagogical narrator; little-women dialogue tagged with affectionate moralism" },
  { slug: "washington-irving", name: "Washington Irving", era: "Pre-1900", hint: "genial antiquarian sketch-book voice; Addisonian leisurely periods; mock-pedantic Knickerbocker drollery" },
  { slug: "james-fenimore-cooper", name: "James Fenimore Cooper", era: "Pre-1900", hint: "frontier romance with stately latinate diction; verbose forest tableau; speechifying scouts and sachems" },
  { slug: "o-henry", name: "O. Henry", era: "Pre-1900", hint: "tight magazine-story arc engineered toward surprise reversal; mock-elevated diction over working-class scenes" },
  { slug: "jack-london", name: "Jack London", era: "Pre-1900", hint: "muscular survival naturalism; short hammered sentences; primal will-to-live in physical detail" },
  { slug: "theodore-dreiser", name: "Theodore Dreiser", era: "Modernist", hint: "lumbering deterministic naturalism; clumsy-on-purpose accumulation of brand names and dollar amounts" },
  { slug: "booth-tarkington", name: "Booth Tarkington", era: "Modernist", hint: "Midwestern small-town comedy of manners; affectionate adolescent free indirect; nostalgic ironic distance" },
  { slug: "joseph-sheridan-le-fanu", name: "Joseph Sheridan Le Fanu", era: "Pre-1900", hint: "Anglo-Irish gothic dread; framed manuscript narrators; slow uncanny closing-in of supernatural detail" },
  { slug: "m-r-james", name: "M.R. James", era: "Modernist", hint: "antiquarian ghost story; donnish offhand narrator; horror revealed in clipped half-glimpses" },
  { slug: "algernon-blackwood", name: "Algernon Blackwood", era: "Modernist", hint: "wilderness numinous-horror; long susurrating sentences building animistic dread" },
  { slug: "walter-scott", name: "Walter Scott", era: "Pre-1900", hint: "historical romance with antiquarian footnotes; Scots dialect set against high English narration" },
  { slug: "maria-edgeworth", name: "Maria Edgeworth", era: "Pre-1900", hint: "Anglo-Irish moral tale; brisk didactic narrator; servant-vernacular framed by gentry irony" },
  { slug: "frances-burney", name: "Frances Burney", era: "Pre-1900", hint: "epistolary debutante satire; breathless first-person letters; sharp social comedy of mortification" },
  { slug: "ann-radcliffe", name: "Ann Radcliffe", era: "Pre-1900", hint: "explained-supernatural gothic; sublime landscape ekphrasis; trembling heroine tested by picturesque terror" },
  { slug: "matthew-lewis", name: "Matthew Lewis", era: "Pre-1900", hint: "luridly transgressive monk-gothic; sensational fast pacing; demonic spectacle without explanation" },
  { slug: "edward-bulwer-lytton", name: "Edward Bulwer-Lytton", era: "Pre-1900", hint: "high-Victorian rhetorical orotundity; opening with weather and abstract noun; melodramatic philosophical aside" },
  { slug: "george-macdonald", name: "George MacDonald", era: "Pre-1900", hint: "Scottish mystic-fantasy parable; childlike numinous imagery; quietly Christian allegorical drift" },
  { slug: "william-morris", name: "William Morris", era: "Pre-1900", hint: "deliberately archaized prose romance; pseudo-medieval syntax with thee/thou; pre-Tolkien dreamworld lexicon" },
  { slug: "john-buchan", name: "John Buchan", era: "Modernist", hint: "clubland chase-thriller; clipped Scottish gentleman narrator; brisk geographic specificity under pursuit" },
  { slug: "saki", name: "Saki", era: "Modernist", hint: "Edwardian drawing-room cruelty; arch epigrams; cat-cool sentence ending in mortal punchline" },
  { slug: "anthony-hope", name: "Anthony Hope", era: "Pre-1900", hint: "Ruritanian swashbuckle; mannered first-person gentleman-adventurer; courtly ironic gallantry" },
  { slug: "e-nesbit", name: "E. Nesbit", era: "Modernist", hint: "children's-magic-realism; conspiratorial narrator addressing kid reader; matter-of-fact handling of impossible things" },
  { slug: "frances-hodgson-burnett", name: "Frances Hodgson Burnett", era: "Modernist", hint: "transformation parable for children; sensory garden-bound prose; dialect-laden cottage speech among posh diction" },
  { slug: "l-m-montgomery", name: "L.M. Montgomery", era: "Modernist", hint: "Prince Edward Island lyricism; effusive adjectival landscape; talkative orphan-protagonist run-on rhapsody" },
  { slug: "joel-chandler-harris", name: "Joel Chandler Harris", era: "Pre-1900", hint: "frame-tale dialect transcription; Uncle Remus trickster cadence inside genteel narrator's introduction" },
  { slug: "mary-e-wilkins-freeman", name: "Mary E. Wilkins Freeman", era: "Pre-1900", hint: "New England spinster realism; spare austere sentences; quiet rebellions inside parsimonious villages" },
  { slug: "jerome-k-jerome", name: "Jerome K. Jerome", era: "Pre-1900", hint: "comic digressive first-person clubman; mock-philosophical tangents collapsing into slapstick anecdote" },
  { slug: "rider-haggard", name: "Rider Haggard", era: "Pre-1900", hint: "imperial lost-world adventure; pseudo-translated manuscript framing; portentous African-tableau diction" },
  { slug: "dostoevsky", name: "Fyodor Dostoevsky", era: "Pre-1900", hint: "feverish polyphony; nested clauses spiraling toward confession; characters interrupting their own thoughts mid-sentence" },
  { slug: "turgenev", name: "Ivan Turgenev", era: "Pre-1900", hint: "lyrical realism; long landscape paragraphs that mirror interior states; restrained elegiac cadence" },
  { slug: "pushkin", name: "Alexander Pushkin", era: "Pre-1900", hint: "crystalline precision; light Mozartian irony; iambic compactness even in prose" },
  { slug: "gogol", name: "Nikolai Gogol", era: "Pre-1900", hint: "grotesque hyperbole and digressive Homeric similes; narrator slips into petty bureaucratic tics; comedy that turns abruptly metaphysical" },
  { slug: "lermontov", name: "Mikhail Lermontov", era: "Pre-1900", hint: "Byronic cool; clipped diaristic clauses laced with bored irony; Caucasus landscapes treated as moral mirrors" },
  { slug: "leskov", name: "Nikolai Leskov", era: "Pre-1900", hint: "skaz narration — story relayed through a vernacular speaker whose idiom and prejudices saturate the prose" },
  { slug: "andreyev", name: "Leonid Andreyev", era: "Modernist", hint: "expressionist allegory; abstract capitalized nouns (Death, Wall) substituted for character; hammering anaphora" },
  { slug: "bunin", name: "Ivan Bunin", era: "Modernist", hint: "olfactory and tactile precision; sentence rhythms that slow at sensory peaks; elegy for the vanished estate" },
  { slug: "andrei-bely", name: "Andrei Bely", era: "Modernist", hint: "Symbolist prose-as-music; recurrent leitmotif phrases, anapestic clause-rhythm, color and number pressed into incantation" },
  { slug: "stendhal", name: "Stendhal", era: "Pre-1900", hint: "crystallization psychology; quick analytic sentences with parenthetical self-correction; Napoleonic clarity over ornament" },
  { slug: "maupassant", name: "Guy de Maupassant", era: "Pre-1900", hint: "tight Flaubertian conte; flat naturalist verbs leading to a single hinge sentence that overturns the story" },
  { slug: "jules-verne", name: "Jules Verne", era: "Pre-1900", hint: "encyclopedic enumeration of measurements, latitudes, machinery; technical specificity used as adventure-engine" },
  { slug: "alexandre-dumas-pere", name: "Alexandre Dumas pere", era: "Pre-1900", hint: "rapid feuilleton dialogue; cliffhanger chapter-ends; swordpoint exposition in short paragraphs" },
  { slug: "gautier", name: "Theophile Gautier", era: "Pre-1900", hint: "art-for-art's-sake; jeweled adjectival catalogues; ekphrastic still-frames where action stops to render surfaces" },
  { slug: "nerval", name: "Gerard de Nerval", era: "Pre-1900", hint: "oneiric drift between dream and memory; first-person voice that conflates real and visionary geography mid-sentence" },
  { slug: "huysmans", name: "Joris-Karl Huysmans", era: "Pre-1900", hint: "decadent maximalism; obsessive lapidary catalogues of perfumes, gems, liturgy; neologism and rare adjective" },
  { slug: "rimbaud", name: "Arthur Rimbaud", era: "Pre-1900", hint: "hallucinated synesthesia; vatic exclamation; rupture of syntax and tense — vowels assigned colors" },
  { slug: "verlaine", name: "Paul Verlaine", era: "Pre-1900", hint: "musique avant toute chose; impair odd-syllable lines; mist and blur over statement; nuance not color" },
  { slug: "verhaeren", name: "Emile Verhaeren", era: "Modernist", hint: "industrial visionary verse; pounding free-verse anaphora on cities, factories, wind; capitalized abstractions" },
  { slug: "goethe", name: "Johann Wolfgang von Goethe", era: "Pre-1900", hint: "Bildung clarity; moves between epistolary inwardness and classical balance; nature-philosophy embedded in image" },
  { slug: "heine", name: "Heinrich Heine", era: "Pre-1900", hint: "lyric folksong rhythm punctured by ironic last-line snap; deflating wit applied to Romantic gesture" },
  { slug: "fontane", name: "Theodor Fontane", era: "Pre-1900", hint: "Plauderton — the chatting tone; social realism via long civilized dialogue; what isn't said in a Berlin drawing-room" },
  { slug: "theodor-storm", name: "Theodor Storm", era: "Pre-1900", hint: "North Sea Novelle; framed reminiscence; coastal weather and dyke imagery threaded as fate" },
  { slug: "stifter", name: "Adalbert Stifter", era: "Pre-1900", hint: "sanftes Gesetz — the gentle law; patient close observation of landscape and weather; ethics expressed through botanical detail" },
  { slug: "keller", name: "Gottfried Keller", era: "Pre-1900", hint: "Swiss village realism with humorous moral ironies; warm omniscient narrator; deliberate slow Bildung pacing" },
  { slug: "kleist", name: "Heinrich von Kleist", era: "Pre-1900", hint: "tightly coiled subordinate clauses delaying the verb; juridical syntax around violent contingency; one-sentence catastrophes" },
  { slug: "novalis", name: "Novalis", era: "Pre-1900", hint: "Romantic fragment and aphorism; mystical inward turn — blue flower; prose that dissolves into hymn" },
  { slug: "droste-hulshoff", name: "Annette von Droste-Hulshoff", era: "Pre-1900", hint: "Westphalian heath imagery; ballad-tight verse rhythm carried into prose; ethical dread under domestic surface" },
  { slug: "manzoni", name: "Alessandro Manzoni", era: "Pre-1900", hint: "Tuscan-purified historical realism; long providential narrator commentary woven into seventeenth-century plot" },
  { slug: "dannunzio", name: "Gabriele D'Annunzio", era: "Modernist", hint: "decadent estheticism; ornate adjective-stacked sentences; sensual Mediterranean color and fin-de-siecle excess" },
  { slug: "leopardi", name: "Giacomo Leopardi", era: "Pre-1900", hint: "philosophical pessimism in luminous canti; cosmic infinity glimpsed from a hilltop; precise classical economy" },
  { slug: "unamuno", name: "Miguel de Unamuno", era: "Modernist", hint: "agonic essayistic voice; nivola — naked dialogue and metaphysical doubt; address to the reader as accomplice" },
  { slug: "leopoldo-alas", name: "Leopoldo Alas (Clarin)", era: "Pre-1900", hint: "free indirect discourse threading provincial gossip into interior life; Flaubertian Spain; corrosive irony" },
  { slug: "strindberg", name: "August Strindberg", era: "Modernist", hint: "dream-play discontinuity; psychological combat in clipped fractured dialogue; naturalism collapsing into expressionist collage" },
  { slug: "hamsun", name: "Knut Hamsun", era: "Modernist", hint: "interior monologue of a starving consciousness; jagged present-tense fragments; irrational impulse foregrounded" },
  { slug: "andersen", name: "Hans Christian Andersen", era: "Pre-1900", hint: "oral fairy-tale cadence; child-direct narrator with sudden bittersweet pivots; objects given small ironic voices" },
  { slug: "jacobsen", name: "Jens Peter Jacobsen", era: "Pre-1900", hint: "atmospheric prose-pointillism; freighted color words and slow sensory pacing; doubt-saturated interiority" },
  { slug: "mickiewicz", name: "Adam Mickiewicz", era: "Pre-1900", hint: "Polish national epic in thirteen-syllable line; nostalgic Lithuanian pastoral; invocation-and-catalogue opening" },
  { slug: "sienkiewicz", name: "Henryk Sienkiewicz", era: "Pre-1900", hint: "panoramic historical romance; sweeping battle tableaux; archaized Polish-knightly diction in dialogue" },
  { slug: "aleksis-kivi", name: "Aleksis Kivi", era: "Pre-1900", hint: "founding Finnish-vernacular prose; biblical-tinged rhythm; forest and brother-band wildness in plain rugged sentences" },
  { slug: "homer", name: "Homer", era: "Pre-1900", hint: "epic hexameter cadence; fixed epithets; extended Homeric similes that swerve into pastoral digression" },
  { slug: "hesiod", name: "Hesiod", era: "Pre-1900", hint: "didactic catalog and genealogy; gnomic farmer's-almanac plainness over mythic scaffolding" },
  { slug: "sappho", name: "Sappho", era: "Pre-1900", hint: "fragmentary lyric in first person; sensory immediacy through ellipses and bracketed lacunae" },
  { slug: "aeschylus", name: "Aeschylus", era: "Pre-1900", hint: "torqued tragic grandeur; compound epithets and choral riddle-language straining the line" },
  { slug: "sophocles", name: "Sophocles", era: "Pre-1900", hint: "stichomythic tightening toward catastrophe; balanced antithesis loaded with dramatic irony" },
  { slug: "euripides", name: "Euripides", era: "Pre-1900", hint: "rhetorical debate-speeches; psychologized monologue spliced with skeptical sententiae" },
  { slug: "aristophanes", name: "Aristophanes", era: "Pre-1900", hint: "vulgar choral exuberance; nonce-coinage and political pun crashing into lyric parody" },
  { slug: "herodotus", name: "Herodotus", era: "Pre-1900", hint: "digressive ethnographic anecdote in Ionic ease; 'they say' hedging and ring composition" },
  { slug: "thucydides", name: "Thucydides", era: "Pre-1900", hint: "compressed analytical syntax; abstract nouns and balanced antithesis in reconstructed speeches" },
  { slug: "plutarch", name: "Plutarch", era: "Pre-1900", hint: "paired biographical portraits; moralizing anecdote and apophthegm rounded into character verdict" },
  { slug: "marcus-aurelius", name: "Marcus Aurelius", era: "Pre-1900", hint: "second-person Stoic self-address; aphoristic fragments commanding the soul" },
  { slug: "epictetus", name: "Epictetus", era: "Pre-1900", hint: "diatribe-style imagined dialogue; blunt imperatives drilling the dichotomy of control" },
  { slug: "cicero", name: "Cicero", era: "Pre-1900", hint: "periodic Latin sentence; tricolon, anaphora, and a final rhythmic clausula releasing the suspense" },
  { slug: "virgil", name: "Virgil", era: "Pre-1900", hint: "stately dactylic gravitas; weighted enjambment and elegiac undertow ('the tears of things')" },
  { slug: "ovid", name: "Ovid", era: "Pre-1900", hint: "elegiac wit; metamorphic transitions hinged on a glittering paradox or pun" },
  { slug: "horace", name: "Horace", era: "Pre-1900", hint: "polished lyric urbanity; Sabine-farm sententiae set inside tightly built Alcaic stanzas" },
  { slug: "catullus", name: "Catullus", era: "Pre-1900", hint: "colloquial hendecasyllabic intimacy; obscene invective and tender lyric in the same breath" },
  { slug: "lucretius", name: "Lucretius", era: "Pre-1900", hint: "didactic hexameter on atoms; honeyed-cup analogy and propulsive Epicurean argument" },
  { slug: "juvenal", name: "Juvenal", era: "Pre-1900", hint: "indignant hexameter satire; cataloged urban grotesques delivered as scornful rhetorical questions" },
  { slug: "tacitus", name: "Tacitus", era: "Pre-1900", hint: "dense Latinate brevity; epigrammatic moral sting and dark sententious closer" },
  { slug: "suetonius", name: "Suetonius", era: "Pre-1900", hint: "rubric-organized imperial biography; gossip and physical detail catalogued without comment" },
  { slug: "caesar", name: "Julius Caesar", era: "Pre-1900", hint: "third-person military dispatch; austere paratactic clarity, every clause load-bearing" },
  { slug: "petronius", name: "Petronius", era: "Pre-1900", hint: "satiric prose-and-verse mosaic; vulgar Latin street register colliding with mock-epic high diction" },
  { slug: "apuleius", name: "Apuleius", era: "Pre-1900", hint: "lush ornamental Latin; archaizing diction studding a picaresque fairy-tale frame" },
  { slug: "lucian", name: "Lucian of Samosata", era: "Pre-1900", hint: "satirical dialogue; deadpan fantastic premise undercut by skeptical Attic wit" },
  { slug: "augustine", name: "Augustine of Hippo", era: "Pre-1900", hint: "second-person address to God; recursive self-interrogation in restless rhetorical questions" },
  { slug: "boethius", name: "Boethius", era: "Pre-1900", hint: "prosimetric dialogue with Lady Philosophy; argumentative prose alternating with consolatory verse" },
  { slug: "snorri-sturluson", name: "Snorri Sturluson", era: "Pre-1900", hint: "saga-prose terseness; kenning-laden mythography reported as if matter-of-fact chronicle" },
  { slug: "saxo-grammaticus", name: "Saxo Grammaticus", era: "Pre-1900", hint: "ornate medieval Latin chronicle; legendary kings rendered with rhetorical flourish and moral aside" },
  { slug: "dante", name: "Dante Alighieri", era: "Pre-1900", hint: "terza rima architecture; vernacular precision joined to scholastic allegory and lapidary closing line" },
  { slug: "boccaccio", name: "Giovanni Boccaccio", era: "Pre-1900", hint: "frame-tale novella in elaborate periodic prose; ironic worldly voice surveying ten days of stories" },
  { slug: "petrarch", name: "Petrarch", era: "Pre-1900", hint: "Italian sonnet octave/sestet turn; oxymoronic love-paradoxes ('icy fire') refined to a single conceit" },
  { slug: "chaucer", name: "Geoffrey Chaucer", era: "Pre-1900", hint: "Middle English iambic couplets; pilgrim-portrait irony and free indirect mimicry of social register" },
  { slug: "malory", name: "Thomas Malory", era: "Pre-1900", hint: "paratactic 'and...and' Arthurian chronicle; ceremonious oaths and laconic battle-report" },
  { slug: "machiavelli", name: "Niccolo Machiavelli", era: "Pre-1900", hint: "cool empirical maxim; 'it is necessary that' pivots from historical example to ruthless precept" },
  { slug: "cervantes", name: "Miguel de Cervantes", era: "Pre-1900", hint: "metafictional frame and parody of chivalric romance; sane-mad voice oscillating across narrator and knight" },
  { slug: "camoes", name: "Luis de Camoes", era: "Pre-1900", hint: "Portuguese epic ottava rima; oceanic voyage rhetoric layered with classical invocation" },
  { slug: "murasaki", name: "Murasaki Shikibu", era: "Pre-1900", hint: "Heian court interiority; allusive seasonal imagery and embedded waka pivoting on a kakekotoba pun" },
  { slug: "sei-shonagon", name: "Sei Shonagon", era: "Pre-1900", hint: "zuihitsu list-fragment ('Things that...'); aestheticized court observation pinned to a single sensory hinge" },
  { slug: "omar-khayyam", name: "Omar Khayyam", era: "Pre-1900", hint: "Fitzgerald-translation quatrain (aaba); carpe-diem fatalism set among roses, wine, and the turning bowl of heaven" },
  { slug: "bacon", name: "Francis Bacon", era: "Pre-1900", hint: "aphoristic Latinate parallels; sentences that crystallise into proverb, balanced clauses pivoting on a colon or semicolon" },
  { slug: "montaigne", name: "Michel de Montaigne", era: "Pre-1900", hint: "digressive 'que sais-je?' essai; first-person doubt drifting through Roman quotation and homely anecdote, self-revising mid-clause" },
  { slug: "pascal", name: "Blaise Pascal", era: "Pre-1900", hint: "pensee fragment — abrupt geometric epigrams that swerve from mathematical clarity to vertiginous spiritual paradox" },
  { slug: "spinoza", name: "Baruch Spinoza", era: "Pre-1900", hint: "more geometrico — definitions, axioms, propositions, QED; deductive prose stripped of rhetorical ornament, every clause a numbered move" },
  { slug: "locke", name: "John Locke", era: "Pre-1900", hint: "patient empiricist exposition; long enumerative sentences anchored on 'plain' and 'idea', building consent clause by clause" },
  { slug: "hume", name: "David Hume", era: "Pre-1900", hint: "ironic balance and Ciceronian poise; sceptical conclusions delivered through symmetrical 'on the one hand / on the other' clauses" },
  { slug: "adam-smith", name: "Adam Smith", era: "Pre-1900", hint: "Scottish-Enlightenment paragraph that braids moral psychology with mercantile fact; long periodic sentences resolving into a maxim" },
  { slug: "burke", name: "Edmund Burke", era: "Pre-1900", hint: "swelling parliamentary period — accumulating subordinate clauses, sublime indignation, triadic crescendos against abstraction" },
  { slug: "paine", name: "Thomas Paine", era: "Pre-1900", hint: "plainspoken pamphlet hammer; short declarative sentences in working-man diction, italics for emphasis, common-sense apostrophe" },
  { slug: "wollstonecraft", name: "Mary Wollstonecraft", era: "Pre-1900", hint: "indignant rationalist polemic; rolling sentences that interrupt themselves with parenthetical scorn at 'pretty trifles' and false delicacy" },
  { slug: "mill", name: "John Stuart Mill", era: "Pre-1900", hint: "utilitarian transparency — long, scrupulously qualified sentences that name the counter-argument inside the same clause" },
  { slug: "carlyle", name: "Thomas Carlyle", era: "Pre-1900", hint: "prophetic Capitalised Abstractions; jagged exclamations, German-inflected inversions, whirlwind apostrophe to History and the Hero" },
  { slug: "ruskin", name: "John Ruskin", era: "Pre-1900", hint: "rapturous architectural list; cathedral-long sentences enumerating stone, leaf, and shadow with moral urgency tucked into the asides" },
  { slug: "pater", name: "Walter Pater", era: "Pre-1900", hint: "aesthete cadence polished to a hard gem-like flame; subordinate clauses delicately inverted, every adjective weighed and placed" },
  { slug: "matthew-arnold", name: "Matthew Arnold", era: "Pre-1900", hint: "high-Victorian touchstone criticism; calm magisterial sentences that repeat key phrases ('sweetness and light', 'the best that has been thought') as refrain" },
  { slug: "bagehot", name: "Walter Bagehot", era: "Pre-1900", hint: "shrewd clubland prose; brisk paradoxes about institutions delivered in the second half of a sentence after a colon" },
  { slug: "de-quincey", name: "Thomas De Quincey", era: "Pre-1900", hint: "impassioned digressive prose; opium-coloured periodic sentences that nest dream within memory within footnote" },
  { slug: "hazlitt", name: "William Hazlitt", era: "Pre-1900", hint: "combative familiar essay; muscular plain English driven by italicised verbs and pugilistic adversative clauses" },
  { slug: "lamb", name: "Charles Lamb", era: "Pre-1900", hint: "Elia's whimsical antiquarian voice; archaisms slipped beside cockney detail, parentheses that sigh and pun" },
  { slug: "macaulay", name: "Thomas Macaulay", era: "Pre-1900", hint: "Whig-historian cannonade; short emphatic declaratives in triplets, bold antitheses, every paragraph a courtroom verdict" },
  { slug: "gibbon", name: "Edward Gibbon", era: "Pre-1900", hint: "ironic imperial period; balanced antithetical clauses, decorous Latinate diction, decline narrated through suave understatement" },
  { slug: "thomas-henry-huxley", name: "Thomas Henry Huxley", era: "Pre-1900", hint: "Darwin's bulldog lecturing in plain muscular English; concrete biological example deployed to detonate a metaphysical claim" },
  { slug: "spencer", name: "Herbert Spencer", era: "Pre-1900", hint: "synthetic-philosophy taxonomy; tireless evolutionary generalisations marshalled into nested 'first / second / third' subordination" },
  { slug: "william-james", name: "William James", era: "Pre-1900", hint: "conversational pragmatist — colloquial buttonholing 'we', vivid metaphor (stream, fringe), parenthetical asides that reopen the argument" },
  { slug: "freud", name: "Sigmund Freud", era: "Modernist", hint: "case-history detective prose; calm clinical narration that lets the uncanny detail land in a subordinate clause" },
  { slug: "marx", name: "Karl Marx", era: "Pre-1900", hint: "Hegelian inversion clause — 'not X that determines Y, but Y that determines X'; dialectical chiasmus carrying historical sarcasm" },
  { slug: "engels", name: "Friedrich Engels", era: "Pre-1900", hint: "factual journalistic militancy; concrete industrial detail (looms, slums, wages) marshalled into rolling polemical paragraphs" },
  { slug: "schopenhauer", name: "Arthur Schopenhauer", era: "Pre-1900", hint: "lucid pessimist aphorism; crisp German periodicity rendered as long single-thought sentences ending in a sting against Hegel or hope" },
  { slug: "kierkegaard", name: "Soren Kierkegaard", era: "Pre-1900", hint: "pseudonymous indirect communication; ironic Socratic asides, italicised paradox ('the leap'), restless self-quoting voices" },
  { slug: "tocqueville", name: "Alexis de Tocqueville", era: "Pre-1900", hint: "patrician sociological survey; long French-balanced sentences that pivot on 'I have observed' before delivering a quiet democratic prophecy" },
  { slug: "henry-adams", name: "Henry Adams", era: "Pre-1900", hint: "third-person autobiographical irony; Bostonian self-deprecation deployed against Virgin and Dynamo, every paragraph a controlled bafflement" },
  { slug: "veblen", name: "Thorstein Veblen", era: "Modernist", hint: "deadpan sociological coinage; mock-scholastic Latinity ('conspicuous consumption', 'pecuniary emulation') buried inside flat declarative sentences" },
  { slug: "booker-t-washington", name: "Booker T. Washington", era: "Pre-1900", hint: "plainspoken uplift autobiography; concrete homely detail, parable-shaped paragraphs that close on a moral imperative" },
  { slug: "du-bois", name: "W.E.B. Du Bois", era: "Modernist", hint: "lyrical prophetic sociology; biblical cadence and double-consciousness antitheses, paragraphs scored like spirituals with refrain" },
  { slug: "darwin", name: "Charles Darwin", era: "Pre-1900", hint: "patient Victorian naturalist exposition; sentences accumulating concrete observations and qualifications until the inference is unavoidable" },
  { slug: "wallace", name: "Alfred Russel Wallace", era: "Pre-1900", hint: "field-collector traveller's prose; clear enumerative sentences that move from species-list to evolutionary generalisation without ornament" },
  { slug: "muir", name: "John Muir", era: "Pre-1900", hint: "ecstatic Sierra rhapsody; present-tense glacial verbs and exclamations, 'glorious' adjectives stacked, granite turned to scripture" },
  { slug: "russell", name: "Bertrand Russell", era: "Modernist", hint: "crystalline analytic prose; short cool sentences, mischievous understatement, abstractions handled like stones turned over in the palm" },
  { slug: "newman", name: "John Henry Newman", era: "Pre-1900", hint: "Oratorian sermon prose; long lucid Ciceronian periods turning a single distinction over and over until conscience is named" },
  { slug: "kropotkin", name: "Peter Kropotkin", era: "Pre-1900", hint: "anarchist field-naturalist; warm conversational register that braids zoological example with mutual-aid moral, dashes and 'we' pulling the reader in" },
  { slug: "william-shakespeare", name: "William Shakespeare", era: "Pre-1900", hint: "iambic pentameter blank verse with strategic prose for low characters; dense metaphor stacking, antithetical couplets, and embedded soliloquy that turns argument into psychology" },
  { slug: "christopher-marlowe", name: "Christopher Marlowe", era: "Pre-1900", hint: "mighty-line blank verse; end-stopped pentameter swelling toward hyperbolic apostrophe and overreacher rhetoric (Tamburlaine-style aspiration)" },
  { slug: "ben-jonson", name: "Ben Jonson", era: "Pre-1900", hint: "humours-comedy with classical scaffolding; satiric type-character names, Latinate diction, and tight epigrammatic pentameter couplets" },
  { slug: "john-webster", name: "John Webster", era: "Pre-1900", hint: "Jacobean revenge tragedy; sententious aphorisms set in glittering darkness, sudden moral apothegms inside grotesque stage business" },
  { slug: "thomas-middleton", name: "Thomas Middleton", era: "Pre-1900", hint: "city-comedy + tragedy hybrid; cynical commercial idiom, sexual double-entendre, and pentameter that breaks midline into thudding monosyllables" },
  { slug: "thomas-kyd", name: "Thomas Kyd", era: "Pre-1900", hint: "proto-revenge melodrama; declamatory blank verse with anaphora and Senecan ghost-speech, balanced rhetorical periods" },
  { slug: "john-ford", name: "John Ford", era: "Pre-1900", hint: "late Caroline tragedy; quiet, glassy blank verse around taboo passion, restraint that detonates in monosyllabic confessions" },
  { slug: "francis-beaumont", name: "Francis Beaumont", era: "Pre-1900", hint: "tragicomic collaboration verse; mock-heroic burlesque (Knight of the Burning Pestle) and metatheatrical citizen-audience interruption" },
  { slug: "john-fletcher", name: "John Fletcher", era: "Pre-1900", hint: "smooth feminine-ending pentameter; tragicomic reversal, courtly wit, ten-syllable lines softened by trailing extra unstressed syllable" },
  { slug: "philip-massinger", name: "Philip Massinger", era: "Pre-1900", hint: "Caroline social-protest drama; orderly oratorical blank verse, declamatory denunciations of greed (A New Way to Pay Old Debts)" },
  { slug: "john-dryden", name: "John Dryden", era: "Pre-1900", hint: "heroic couplets in iambic pentameter; balanced antithesis, Augustan rational-satiric voice, end-stopped epigrammatic close" },
  { slug: "william-congreve", name: "William Congreve", era: "Pre-1900", hint: "Restoration comedy of manners; polished prose epigram, paradox, and the marriage-contract scene as duelling wit" },
  { slug: "william-wycherley", name: "William Wycherley", era: "Pre-1900", hint: "harsh Restoration satire; bawdy double-entendre under polite syntax, cuckoldry plotting and acid moral inversion" },
  { slug: "george-etherege", name: "George Etherege", era: "Pre-1900", hint: "Restoration libertine comedy; languid courtly prose, fop-versus-rake antithesis, urbane scene-painting of Mall and parlour" },
  { slug: "john-vanbrugh", name: "John Vanbrugh", era: "Pre-1900", hint: "late-Restoration social comedy; brisk colloquial prose, marriage-as-cage premise, and architecturally symmetrical plot reversals" },
  { slug: "aphra-behn", name: "Aphra Behn", era: "Pre-1900", hint: "Restoration intrigue comedy + frank erotic verse; rapid masquerade plotting, free-flowing pentameter, female-libertine voice" },
  { slug: "thomas-otway", name: "Thomas Otway", era: "Pre-1900", hint: "she-tragedy pathos; soft pentameter weeping into broken half-lines, conjugal grief as the dramatic engine (Venice Preserved)" },
  { slug: "richard-brinsley-sheridan", name: "Richard Brinsley Sheridan", era: "Pre-1900", hint: "late-18th-century comedy of manners; aphoristic prose epigram, satire of sentimentalism, set-piece screen scenes (School for Scandal)" },
  { slug: "oliver-goldsmith", name: "Oliver Goldsmith", era: "Pre-1900", hint: "laughing-comedy revival; warm plain prose, mistaken-identity farce, and heroic couplets of pastoral nostalgia (Deserted Village)" },
  { slug: "alexander-pope", name: "Alexander Pope", era: "Pre-1900", hint: "heroic couplet at maximum polish; zeugma, mock-epic miniaturisation, caesura placed for satiric snap, ten syllables that bite" },
  { slug: "john-milton", name: "John Milton", era: "Pre-1900", hint: "unrhymed iambic pentameter epic; long Latinate periodic sentences enjambed across many lines, inverted syntax, sublime cosmic register" },
  { slug: "john-donne", name: "John Donne", era: "Pre-1900", hint: "metaphysical conceit; rough-stressed accentual pentameter, dramatic colloquial opening (Batter my heart), extended scientific/erotic analogy" },
  { slug: "george-herbert", name: "George Herbert", era: "Pre-1900", hint: "devotional plain style; shaped/pattern poems, quiet stanzaic argument that resolves on a single tendered monosyllable" },
  { slug: "andrew-marvell", name: "Andrew Marvell", era: "Pre-1900", hint: "octosyllabic tetrameter couplets; cool wit balancing pastoral and political, dialectical stanza moving thesis to volta" },
  { slug: "edmund-spenser", name: "Edmund Spenser", era: "Pre-1900", hint: "Spenserian stanza (eight pentameters + alexandrine, ababbcbcc); archaising diction, allegorical knight-procession, slow musical sweetness" },
  { slug: "philip-sidney", name: "Sir Philip Sidney", era: "Pre-1900", hint: "Elizabethan sonnet sequence; courtly Petrarchism with self-mocking turns (Astrophil), quantitative-meter experiment, defence-of-poesy register" },
  { slug: "robert-herrick", name: "Robert Herrick", era: "Pre-1900", hint: "Cavalier lyric miniature; trim tetrameter and trimeter couplets, carpe-diem tropes (gather ye rosebuds), pastoral-erotic compression" },
  { slug: "robert-burns", name: "Robert Burns", era: "Pre-1900", hint: "Scots vernacular lyric; standard Habbie stanza (aaabab), rolling dialect rhyme, song-fitted ballad meter and folk address" },
  { slug: "william-blake", name: "William Blake", era: "Pre-1900", hint: "Songs-style hymnal quatrains and prophetic free-verse septenaries; visionary symbolic system, contraries (Innocence/Experience), trochaic insistence" },
  { slug: "william-cowper", name: "William Cowper", era: "Pre-1900", hint: "domestic Augustan blank verse and hymnody; meditative middle-style pentameter (The Task), Olney-Hymn quatrains of evangelical plainness" },
  { slug: "william-wordsworth", name: "William Wordsworth", era: "Pre-1900", hint: "blank-verse meditative autobiography; plain selection of language really used by men, recollection-in-tranquillity arc, slow paragraph-long pentameter" },
  { slug: "samuel-taylor-coleridge", name: "Samuel Taylor Coleridge", era: "Pre-1900", hint: "ballad meter for the supernatural (Rime) plus conversational blank-verse interiors; accentual experiment in Christabel, dream-symbol charge" },
  { slug: "john-keats", name: "John Keats", era: "Pre-1900", hint: "ode-stanza of his own design (10-line iambic pentameter, ababcdecde); negative capability, synaesthetic sensuous adjective stack" },
  { slug: "lord-byron", name: "Lord Byron", era: "Pre-1900", hint: "ottava rima satire (abababcc) in Don Juan; conversational digression, mock-heroic deflation, Byronic-hero brooding pentameter elsewhere" },
  { slug: "percy-shelley", name: "Percy Bysshe Shelley", era: "Pre-1900", hint: "terza rima and elaborate ode stanzas; abstract Platonising vocabulary, west-wind invocation, rapid enjambed cascading clauses" },
  { slug: "alfred-tennyson", name: "Alfred Lord Tennyson", era: "Pre-1900", hint: "Victorian musical phonics; In-Memoriam abba tetrameter stanza, heavy alliteration and vowel-tuning, dramatic monologue (Ulysses) close" },
  { slug: "robert-browning", name: "Robert Browning", era: "Pre-1900", hint: "dramatic monologue with unreliable speaker; rough enjambed pentameter, parenthetical self-interruption, single-listener scene (My Last Duchess)" },
  { slug: "elizabeth-barrett-browning", name: "Elizabeth Barrett Browning", era: "Pre-1900", hint: "Petrarchan sonnet sequence (Sonnets from the Portuguese); novel-in-verse blank pentameter (Aurora Leigh), feminist reformist accent" },
  { slug: "gerard-manley-hopkins", name: "Gerard Manley Hopkins", era: "Pre-1900", hint: "sprung rhythm with stress-counted feet; piled stresses, Welsh cynghanedd consonant clusters, inscape/instress kennings" },
  { slug: "william-butler-yeats", name: "W.B. Yeats", era: "Modernist", hint: "Anglo-Irish symbolist late-Romantic to spare modernist; tetrameter-pentameter ottava rima and quatrains, gyre/mask system, aphoristic close on a hard noun" },
];
