/**
 * Generate Recraft vector cover illustrations for each guide via the worker's
 * /v1/images/generate route (which goes through the AI binding + AI Gateway).
 *
 *   doppler run -- npx tsx scripts/generate-covers.ts
 *
 * The worker must be running locally (npm run dev) — the script POSTs to
 * the dev server, lets the worker call recraft/recraftv4-vector through
 * Workers AI, then downloads the resulting SVG and writes it to
 * public/covers/{slug}.svg.
 *
 * Flags:
 *   --base=http://localhost:5173    dev server URL (default 5173)
 *   --limit=N                        cap how many prompts to run (default: all)
 *   --force                          regenerate covers that already exist
 */

import { existsSync, mkdirSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { COVER_PROMPTS, type CoverPrompt } from "./cover-prompts";

const ROOT = new URL("..", import.meta.url).pathname;
const COVERS_DIR = join(ROOT, "public/covers");
const COVERS_INDEX = join(ROOT, "client/lib/covers.ts");

type Args = {
  base: string;
  limit?: number;
  force: boolean;
};

function parseArgs(argv: string[]): Args {
  const out: Args = {
    base: "http://localhost:5173",
    force: false,
  };
  for (const a of argv) {
    if (a === "--force") {
      out.force = true;
    } else if (a.startsWith("--limit=")) {
      out.limit = Number(a.split("=")[1]);
    } else if (a.startsWith("--base=")) {
      out.base = a.split("=")[1] ?? out.base;
    }
  }
  return out;
}

// Recraft V4 Vector emits the canvas as the first <path> drawn in the file:
// it always starts at (0,0), traces the viewBox edges, and closes back at
// (0,0). The path data sometimes contains straight L segments only, and
// sometimes mixes L with cubic-Bezier C curves where a subject silhouette
// meets the canvas edge. The one stable signature across both shapes is
// "first <path> in the file whose d attribute begins with M 0 0" — that's
// always the bone-white background fill, and stripping it leaves the SVG
// transparent so the card surface shows through.
//
// d attributes never contain literal quote characters, so [^"]* is a safe
// non-greedy match across multi-line paths.
const BG_PATH_RE = /<path\s+d="M\s+0\s+0[^"]*"[^>]*><\/path>/;

function stripBackground(svg: string): { svg: string; stripped: boolean } {
  const next = svg.replace(BG_PATH_RE, "");
  return { svg: next, stripped: next.length !== svg.length };
}

async function generateOne(
  base: string,
  p: CoverPrompt
): Promise<{ svg: string; stripped: boolean }> {
  const r = await fetch(`${base}/v1/images/generate`, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      prompt: p.prompt,
      model: "recraft/recraftv4-vector",
    }),
  });
  if (!r.ok) {
    throw new Error(`worker ${r.status}: ${(await r.text()).slice(0, 400)}`);
  }
  const data = (await r.json()) as { result?: { image?: string } };
  const url = data.result?.image;
  if (!url) {
    throw new Error(`no image url in response: ${JSON.stringify(data).slice(0, 400)}`);
  }
  const svgRes = await fetch(url);
  if (!svgRes.ok) {
    throw new Error(`download ${svgRes.status} for ${p.slug}`);
  }
  const raw = await svgRes.text();
  return stripBackground(raw);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!existsSync(COVERS_DIR)) {
    mkdirSync(COVERS_DIR, { recursive: true });
  }

  const todo = COVER_PROMPTS.filter(
    (p) => args.force || !existsSync(join(COVERS_DIR, `${p.slug}.svg`))
  ).slice(0, args.limit ?? COVER_PROMPTS.length);

  console.log(
    `[covers] base=${args.base} todo=${todo.length}/${COVER_PROMPTS.length} force=${args.force}`
  );

  for (const p of todo) {
    const start = Date.now();
    try {
      const { svg, stripped } = await generateOne(args.base, p);
      writeFileSync(join(COVERS_DIR, `${p.slug}.svg`), svg);
      console.log(
        `  ok:   ${p.slug}  ${(svg.length / 1024).toFixed(1)}kb  ${Date.now() - start}ms${stripped ? "" : "  (bg not stripped — check pattern)"}`
      );
    } catch (e) {
      console.log(`  fail: ${p.slug}  ${(e as Error).message.slice(0, 200)}`);
    }
  }

  writeIndex();
}

// Mirror the on-disk SVG list into client/lib/covers.ts so React
// components can know which slugs have a cover without doing a fetch
// probe at render time. Regenerated on every script run.
function writeIndex() {
  const slugs = readdirSync(COVERS_DIR)
    .filter((f) => f.endsWith(".svg"))
    .map((f) => f.replace(/\.svg$/, ""))
    .sort();
  const content = `// AUTO-GENERATED by scripts/generate-covers.ts. Do not edit by hand.
// Regenerated on every cover-batch run from the contents of public/covers/.

export const COVERED: ReadonlySet<string> = new Set([
${slugs.map((s) => `  ${JSON.stringify(s)},`).join("\n")}
]);
`;
  writeFileSync(COVERS_INDEX, content);
  console.log(`[covers] wrote ${COVERS_INDEX} with ${slugs.length} slugs`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
